# Docker file that uses an external MariaDB
# NPM built by the script -> Slow start

FROM alpine:3.11

RUN apk add --no-cache --update nodejs npm mysql-client git python3 python3-dev gcc g++ unixodbc-dev curl
RUN pip3 install --upgrade pip

RUN mkdir /code
WORKDIR /code
COPY set_privileges.sql /code/set_privileges.sql

# Copy the starting app
COPY runapp.sh /code
RUN chmod +x /code/runapp.sh

# Start the application
ENTRYPOINT [ "/code/runapp.sh"]
EXPOSE 3001 3000